# Testing out circlci config.yml
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.3
    working_directory: /go/src/github.com/stmcallister/go-pagerduty
    steps:
      - checkout
      - run:
          name: "Build"
          command: make build
